=== aRustyDev/homebrew-tap/.data/formula.schema.json
{
  "$id": "https://github.com/aRustyDev/homebrew-tap/formula",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "name": "formula.json",
  "title": "Schema for homebrew formula items",
  "url": "https://raw.githubusercontent.com/aRustyDev/homebrew-tap/main/.data/formula.json",
  "fileMatch": ["formula.json"],
  "type": "object",
  "properties": {
    "owner": {
      "type": "string"
    },
    "repo": {
      "type": "string"
    },
    "formula": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "latest": {
      "type": "string"
    },
    "updated": {
      "type": "string"
    },
    "languages": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    },
    "license": {
      "enum": [
        "0bsd",
        "3d-slicer-1.0",
        "aal",
        "abstyles",
        "adacore-doc",
        "adobe-2006",
        "adobe-display-postscript",
        "adobe-glyph",
        "adobe-utopia",
        "adsl",
        "afl-1.1",
        "afl-1.2",
        "afl-2.0",
        "afl-2.1",
        "afl-3.0",
        "afmparse",
        "agpl-1.0",
        "agpl-1.0-only",
        "agpl-1.0-or-later",
        "agpl-3.0",
        "agpl-3.0-only",
        "agpl-3.0-or-later",
        "aladdin",
        "amd-newlib",
        "amdplpa",
        "aml",
        "aml-glslang",
        "ampas",
        "antlr-pd",
        "antlr-pd-fallback",
        "any-osi",
        "any-osi-perl-modules",
        "apache-1.0",
        "apache-1.1",
        "apache-2.0",
        "apafml",
        "apl-1.0",
        "app-s2p",
        "apsl-1.0",
        "apsl-1.1",
        "apsl-1.2",
        "apsl-2.0",
        "arphic-1999",
        "artistic-1.0",
        "artistic-1.0-cl8",
        "artistic-1.0-perl",
        "artistic-2.0",
        "artistic-dist",
        "aspell-ru",
        "aswf-digital-assets-1.0",
        "aswf-digital-assets-1.1",
        "baekmuk",
        "bahyph",
        "barr",
        "bcrypt-solar-designer",
        "beerware",
        "bitstream-charter",
        "bitstream-vera",
        "bittorrent-1.0",
        "bittorrent-1.1",
        "blessing",
        "blueoak-1.0.0",
        "boehm-gc",
        "boehm-gc-without-fee",
        "borceux",
        "brian-gladman-2-clause",
        "brian-gladman-3-clause",
        "bsd-1-clause",
        "bsd-2-clause",
        "bsd-2-clause-darwin",
        "bsd-2-clause-first-lines",
        "bsd-2-clause-freebsd",
        "bsd-2-clause-netbsd",
        "bsd-2-clause-patent",
        "bsd-2-clause-pkgconf-disclaimer",
        "bsd-2-clause-views",
        "bsd-3-clause",
        "bsd-3-clause-acpica",
        "bsd-3-clause-attribution",
        "bsd-3-clause-clear",
        "bsd-3-clause-flex",
        "bsd-3-clause-hp",
        "bsd-3-clause-lbnl",
        "bsd-3-clause-modification",
        "bsd-3-clause-no-military-license",
        "bsd-3-clause-no-nuclear-license",
        "bsd-3-clause-no-nuclear-license-2014",
        "bsd-3-clause-no-nuclear-warranty",
        "bsd-3-clause-open-mpi",
        "bsd-3-clause-sun",
        "bsd-4-clause",
        "bsd-4-clause-shortened",
        "bsd-4-clause-uc",
        "bsd-4.3reno",
        "bsd-4.3tahoe",
        "bsd-advertising-acknowledgement",
        "bsd-attribution-hpnd-disclaimer",
        "bsd-inferno-nettverk",
        "bsd-protection",
        "bsd-source-beginning-file",
        "bsd-source-code",
        "bsd-systemics",
        "bsd-systemics-w3works",
        "bsl-1.0",
        "busl-1.1",
        "bzip2-1.0.5",
        "bzip2-1.0.6",
        "c-uda-1.0",
        "cal-1.0",
        "cal-1.0-combined-work-exception",
        "caldera",
        "caldera-no-preamble",
        "catharon",
        "catosl-1.1",
        "cc-by-1.0",
        "cc-by-2.0",
        "cc-by-2.5",
        "cc-by-2.5-au",
        "cc-by-3.0",
        "cc-by-3.0-at",
        "cc-by-3.0-au",
        "cc-by-3.0-de",
        "cc-by-3.0-igo",
        "cc-by-3.0-nl",
        "cc-by-3.0-us",
        "cc-by-4.0",
        "cc-by-nc-1.0",
        "cc-by-nc-2.0",
        "cc-by-nc-2.5",
        "cc-by-nc-3.0",
        "cc-by-nc-3.0-de",
        "cc-by-nc-4.0",
        "cc-by-nc-nd-1.0",
        "cc-by-nc-nd-2.0",
        "cc-by-nc-nd-2.5",
        "cc-by-nc-nd-3.0",
        "cc-by-nc-nd-3.0-de",
        "cc-by-nc-nd-3.0-igo",
        "cc-by-nc-nd-4.0",
        "cc-by-nc-sa-1.0",
        "cc-by-nc-sa-2.0",
        "cc-by-nc-sa-2.0-de",
        "cc-by-nc-sa-2.0-fr",
        "cc-by-nc-sa-2.0-uk",
        "cc-by-nc-sa-2.5",
        "cc-by-nc-sa-3.0",
        "cc-by-nc-sa-3.0-de",
        "cc-by-nc-sa-3.0-igo",
        "cc-by-nc-sa-4.0",
        "cc-by-nd-1.0",
        "cc-by-nd-2.0",
        "cc-by-nd-2.5",
        "cc-by-nd-3.0",
        "cc-by-nd-3.0-de",
        "cc-by-nd-4.0",
        "cc-by-sa-1.0",
        "cc-by-sa-2.0",
        "cc-by-sa-2.0-uk",
        "cc-by-sa-2.1-jp",
        "cc-by-sa-2.5",
        "cc-by-sa-3.0",
        "cc-by-sa-3.0-at",
        "cc-by-sa-3.0-de",
        "cc-by-sa-3.0-igo",
        "cc-by-sa-4.0",
        "cc-pddc",
        "cc-pdm-1.0",
        "cc-sa-1.0",
        "cc0-1.0",
        "cddl-1.0",
        "cddl-1.1",
        "cdl-1.0",
        "cdla-permissive-1.0",
        "cdla-permissive-2.0",
        "cdla-sharing-1.0",
        "cecill-1.0",
        "cecill-1.1",
        "cecill-2.0",
        "cecill-2.1",
        "cecill-b",
        "cecill-c",
        "cern-ohl-1.1",
        "cern-ohl-1.2",
        "cern-ohl-p-2.0",
        "cern-ohl-s-2.0",
        "cern-ohl-w-2.0",
        "cfitsio",
        "check-cvs",
        "checkmk",
        "clartistic",
        "clips",
        "cmu-mach",
        "cmu-mach-nodoc",
        "cnri-jython",
        "cnri-python",
        "cnri-python-gpl-compatible",
        "coil-1.0",
        "community-spec-1.0",
        "condor-1.1",
        "copyleft-next-0.3.0",
        "copyleft-next-0.3.1",
        "cornell-lossless-jpeg",
        "cpal-1.0",
        "cpl-1.0",
        "cpol-1.02",
        "cronyx",
        "crossword",
        "cryptoswift",
        "crystalstacker",
        "cua-opl-1.0",
        "cube",
        "curl",
        "cve-tou",
        "d-fsl-1.0",
        "dec-3-clause",
        "diffmark",
        "dl-de-by-2.0",
        "dl-de-zero-2.0",
        "doc",
        "docbook-dtd",
        "docbook-schema",
        "docbook-stylesheet",
        "docbook-xml",
        "dotseqn",
        "drl-1.0",
        "drl-1.1",
        "dsdp",
        "dtoa",
        "dvipdfm",
        "ecl-1.0",
        "ecl-2.0",
        "ecos-2.0",
        "efl-1.0",
        "efl-2.0",
        "egenix",
        "elastic-2.0",
        "entessa",
        "epics",
        "epl-1.0",
        "epl-2.0",
        "erlpl-1.1",
        "etalab-2.0",
        "eudatagrid",
        "eupl-1.0",
        "eupl-1.1",
        "eupl-1.2",
        "eurosym",
        "fair",
        "fbm",
        "fdk-aac",
        "ferguson-twofish",
        "frameworx-1.0",
        "freebsd-doc",
        "freeimage",
        "fsfap",
        "fsfap-no-warranty-disclaimer",
        "fsful",
        "fsfullr",
        "fsfullrsd",
        "fsfullrwd",
        "fsl-1.1-alv2",
        "fsl-1.1-mit",
        "ftl",
        "furuseth",
        "fwlw",
        "game-programming-gems",
        "gcr-docs",
        "gd",
        "generic-xts",
        "gfdl-1.1",
        "gfdl-1.1-invariants-only",
        "gfdl-1.1-invariants-or-later",
        "gfdl-1.1-no-invariants-only",
        "gfdl-1.1-no-invariants-or-later",
        "gfdl-1.1-only",
        "gfdl-1.1-or-later",
        "gfdl-1.2",
        "gfdl-1.2-invariants-only",
        "gfdl-1.2-invariants-or-later",
        "gfdl-1.2-no-invariants-only",
        "gfdl-1.2-no-invariants-or-later",
        "gfdl-1.2-only",
        "gfdl-1.2-or-later",
        "gfdl-1.3",
        "gfdl-1.3-invariants-only",
        "gfdl-1.3-invariants-or-later",
        "gfdl-1.3-no-invariants-only",
        "gfdl-1.3-no-invariants-or-later",
        "gfdl-1.3-only",
        "gfdl-1.3-or-later",
        "giftware",
        "gl2ps",
        "glide",
        "glulxe",
        "glwtpl",
        "gnuplot",
        "gpl-1.0",
        "gpl-1.0+",
        "gpl-1.0-only",
        "gpl-1.0-or-later",
        "gpl-2.0",
        "gpl-2.0+",
        "gpl-2.0-only",
        "gpl-2.0-or-later",
        "gpl-2.0-with-autoconf-exception",
        "gpl-2.0-with-bison-exception",
        "gpl-2.0-with-classpath-exception",
        "gpl-2.0-with-font-exception",
        "gpl-2.0-with-gcc-exception",
        "gpl-3.0",
        "gpl-3.0+",
        "gpl-3.0-only",
        "gpl-3.0-or-later",
        "gpl-3.0-with-autoconf-exception",
        "gpl-3.0-with-gcc-exception",
        "graphics-gems",
        "gsoap-1.3b",
        "gtkbook",
        "gutmann",
        "haskellreport",
        "hdf5",
        "hdparm",
        "hidapi",
        "hippocratic-2.1",
        "hp-1986",
        "hp-1989",
        "hpnd",
        "hpnd-dec",
        "hpnd-doc",
        "hpnd-doc-sell",
        "hpnd-export-us",
        "hpnd-export-us-acknowledgement",
        "hpnd-export-us-modify",
        "hpnd-export2-us",
        "hpnd-fenneberg-livingston",
        "hpnd-inria-imag",
        "hpnd-intel",
        "hpnd-kevlin-henney",
        "hpnd-markus-kuhn",
        "hpnd-merchantability-variant",
        "hpnd-mit-disclaimer",
        "hpnd-netrek",
        "hpnd-pbmplus",
        "hpnd-sell-mit-disclaimer-xserver",
        "hpnd-sell-regexpr",
        "hpnd-sell-variant",
        "hpnd-sell-variant-mit-disclaimer",
        "hpnd-sell-variant-mit-disclaimer-rev",
        "hpnd-uc",
        "hpnd-uc-export-us",
        "htmltidy",
        "ibm-pibs",
        "icu",
        "iec-code-components-eula",
        "ijg",
        "ijg-short",
        "imagemagick",
        "imatix",
        "imlib2",
        "info-zip",
        "inner-net-2.0",
        "innosetup",
        "intel",
        "intel-acpi",
        "interbase-1.0",
        "ipa",
        "ipl-1.0",
        "isc",
        "isc-veillard",
        "jam",
        "jasper-2.0",
        "jove",
        "jpl-image",
        "jpnic",
        "json",
        "kastrup",
        "kazlib",
        "knuth-ctan",
        "lal-1.2",
        "lal-1.3",
        "latex2e",
        "latex2e-translated-notice",
        "leptonica",
        "lgpl-2.0",
        "lgpl-2.0+",
        "lgpl-2.0-only",
        "lgpl-2.0-or-later",
        "lgpl-2.1",
        "lgpl-2.1+",
        "lgpl-2.1-only",
        "lgpl-2.1-or-later",
        "lgpl-3.0",
        "lgpl-3.0+",
        "lgpl-3.0-only",
        "lgpl-3.0-or-later",
        "lgpllr",
        "libpng",
        "libpng-1.6.35",
        "libpng-2.0",
        "libselinux-1.0",
        "libtiff",
        "libutil-david-nugent",
        "liliq-p-1.1",
        "liliq-r-1.1",
        "liliq-rplus-1.1",
        "linux-man-pages-1-para",
        "linux-man-pages-copyleft",
        "linux-man-pages-copyleft-2-para",
        "linux-man-pages-copyleft-var",
        "linux-openib",
        "loop",
        "lpd-document",
        "lpl-1.0",
        "lpl-1.02",
        "lppl-1.0",
        "lppl-1.1",
        "lppl-1.2",
        "lppl-1.3a",
        "lppl-1.3c",
        "lsof",
        "lucida-bitmap-fonts",
        "lzma-sdk-9.11-to-9.20",
        "lzma-sdk-9.22",
        "mackerras-3-clause",
        "mackerras-3-clause-acknowledgment",
        "magaz",
        "mailprio",
        "makeindex",
        "man2html",
        "martin-birgmeier",
        "mcphee-slideshow",
        "metamail",
        "minpack",
        "mips",
        "miros",
        "mit",
        "mit-0",
        "mit-advertising",
        "mit-click",
        "mit-cmu",
        "mit-enna",
        "mit-feh",
        "mit-festival",
        "mit-khronos-old",
        "mit-modern-variant",
        "mit-open-group",
        "mit-testregex",
        "mit-wu",
        "mitnfa",
        "mmixware",
        "motosoto",
        "mpeg-ssg",
        "mpi-permissive",
        "mpich2",
        "mpl-1.0",
        "mpl-1.1",
        "mpl-2.0",
        "mpl-2.0-no-copyleft-exception",
        "mplus",
        "ms-lpl",
        "ms-pl",
        "ms-rl",
        "mtll",
        "mulanpsl-1.0",
        "mulanpsl-2.0",
        "multics",
        "mup",
        "naist-2003",
        "nasa-1.3",
        "naumen",
        "nbpl-1.0",
        "ncbi-pd",
        "ncgl-uk-2.0",
        "ncl",
        "ncsa",
        "net-snmp",
        "netcdf",
        "newsletr",
        "ngpl",
        "ngrep",
        "nicta-1.0",
        "nist-pd",
        "nist-pd-fallback",
        "nist-software",
        "nlod-1.0",
        "nlod-2.0",
        "nlpl",
        "nokia",
        "nosl",
        "noweb",
        "npl-1.0",
        "npl-1.1",
        "nposl-3.0",
        "nrl",
        "ntia-pd",
        "ntp",
        "ntp-0",
        "nunit",
        "o-uda-1.0",
        "oar",
        "occt-pl",
        "oclc-2.0",
        "odbl-1.0",
        "odc-by-1.0",
        "offis",
        "ofl-1.0",
        "ofl-1.0-no-rfn",
        "ofl-1.0-rfn",
        "ofl-1.1",
        "ofl-1.1-no-rfn",
        "ofl-1.1-rfn",
        "ogc-1.0",
        "ogdl-taiwan-1.0",
        "ogl-canada-2.0",
        "ogl-uk-1.0",
        "ogl-uk-2.0",
        "ogl-uk-3.0",
        "ogtsl",
        "oldap-1.1",
        "oldap-1.2",
        "oldap-1.3",
        "oldap-1.4",
        "oldap-2.0",
        "oldap-2.0.1",
        "oldap-2.1",
        "oldap-2.2",
        "oldap-2.2.1",
        "oldap-2.2.2",
        "oldap-2.3",
        "oldap-2.4",
        "oldap-2.5",
        "oldap-2.6",
        "oldap-2.7",
        "oldap-2.8",
        "olfl-1.3",
        "oml",
        "openpbs-2.3",
        "openssl",
        "openssl-standalone",
        "openvision",
        "opl-1.0",
        "opl-uk-3.0",
        "opubl-1.0",
        "oset-pl-2.1",
        "osl-1.0",
        "osl-1.1",
        "osl-2.0",
        "osl-2.1",
        "osl-3.0",
        "padl",
        "parity-6.0.0",
        "parity-7.0.0",
        "pddl-1.0",
        "php-3.0",
        "php-3.01",
        "pixar",
        "pkgconf",
        "plexus",
        "pnmstitch",
        "polyform-noncommercial-1.0.0",
        "polyform-small-business-1.0.0",
        "postgresql",
        "ppl",
        "psf-2.0",
        "psfrag",
        "psutils",
        "python-2.0",
        "python-2.0.1",
        "python-ldap",
        "qhull",
        "qpl-1.0",
        "qpl-1.0-inria-2004",
        "radvd",
        "rdisc",
        "rhecos-1.1",
        "rpl-1.1",
        "rpl-1.5",
        "rpsl-1.0",
        "rsa-md",
        "rscpl",
        "ruby",
        "ruby-pty",
        "sax-pd",
        "sax-pd-2.0",
        "saxpath",
        "scea",
        "schemereport",
        "sendmail",
        "sendmail-8.23",
        "sendmail-open-source-1.1",
        "sgi-b-1.0",
        "sgi-b-1.1",
        "sgi-b-2.0",
        "sgi-opengl",
        "sgp4",
        "shl-0.5",
        "shl-0.51",
        "simpl-2.0",
        "sissl",
        "sissl-1.2",
        "sl",
        "sleepycat",
        "smail-gpl",
        "smlnj",
        "smppl",
        "snia",
        "snprintf",
        "sofa",
        "softsurfer",
        "soundex",
        "spencer-86",
        "spencer-94",
        "spencer-99",
        "spl-1.0",
        "ssh-keyscan",
        "ssh-openssh",
        "ssh-short",
        "ssleay-standalone",
        "sspl-1.0",
        "standardml-nj",
        "sugarcrm-1.1.3",
        "sul-1.0",
        "sun-ppp",
        "sun-ppp-2000",
        "sunpro",
        "swl",
        "swrule",
        "symlinks",
        "tapr-ohl-1.0",
        "tcl",
        "tcp-wrappers",
        "termreadkey",
        "tgppl-1.0",
        "thirdeye",
        "threeparttable",
        "tmate",
        "torque-1.1",
        "tosl",
        "tpdl",
        "tpl-1.0",
        "trustedqsl",
        "ttwl",
        "ttyp0",
        "tu-berlin-1.0",
        "tu-berlin-2.0",
        "ubuntu-font-1.0",
        "ucar",
        "ucl-1.0",
        "ulem",
        "umich-merit",
        "unicode-3.0",
        "unicode-dfs-2015",
        "unicode-dfs-2016",
        "unicode-tou",
        "unixcrypt",
        "unlicense",
        "unlicense-libtelnet",
        "unlicense-libwhirlpool",
        "upl-1.0",
        "urt-rle",
        "vim",
        "vostrom",
        "vsl-1.0",
        "w3c",
        "w3c-19980720",
        "w3c-20150513",
        "w3m",
        "watcom-1.0",
        "widget-workshop",
        "wsuipa",
        "wtfpl",
        "wwl",
        "wxwindows",
        "x11",
        "x11-distribute-modifications-variant",
        "x11-swapped",
        "xdebug-1.03",
        "xerox",
        "xfig",
        "xfree86-1.1",
        "xinetd",
        "xkeyboard-config-zinoviev",
        "xlock",
        "xnet",
        "xpp",
        "xskat",
        "xzoom",
        "ypl-1.0",
        "ypl-1.1",
        "zed",
        "zeeff",
        "zend-2.0",
        "zimbra-1.3",
        "zimbra-1.4",
        "zlib",
        "zlib-acknowledgement",
        "zpl-1.1",
        "zpl-2.0",
        "zpl-2.1"
      ]
    },
    "versions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "enum": ["tag", "release"]
          },
          "name": {
            "type": "string"
          },
          "updated": {
            "type": "string"
          },
          "sha256": {
            "type": "string"
          }
        },
        "required": ["type", "name", "updated", "sha256"]
      }
    }
  },
  "required": [
    "owner",
    "repo",
    "formula",
    "description",
    "latest",
    "license",
    "versions",
    "updated"
  ]
}

=== aRustyDev/homebrew-tap/.data/formula.json
[
  {
    "owner": "rubiojr",
    "repo": "zed-prompts",
    "formula": "zed-prompts",
    "description": "Import and export prompts from Zed's prompt library",
    "latest": "v0.1.3",
    "updated": "2025-01-01",
    "languages": ["go"],
    "license": "mit",
    "versions": [
      {
        "type": "tag",
        "name": "v0.1.3",
        "updated": "2025-01-01",
        "sha256": "df1614deeb7f63b0bbfb9c2dd7c06a526b789f0f3858eddceb3e59a15323bca5"
      }
    ]
  }
]
